version: '3'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=simple_bank
  api:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - DB_SOURCE=postgresql://root:123456@localhost:5432/simplebank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["./wait-for.sh", "postgres:5432", "--", "./start.sh"]
    command: ["./app"]