version: '3'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8088:8088"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:123456@localhost:5432/simplebank?sslmode=disable
      - REDIS_ADDRESS = redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: ["./wait-for.sh", "postgres:5432", "--", "./start.sh"]
    command: ["./app"]

volumes:
  data-volume: